'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {pool,all,one,run,transaction,initialize,schema}=require('./database');
const root=__dirname,now=()=>new Date().toISOString();
const production=process.env.NODE_ENV==='production';
const seedPin=process.env.SEED_PIN||'1234';
if(production&&(!/^\d{8,12}$/.test(seedPin)||/^(\d)\1+$/.test(seedPin)))throw new Error('Set SEED_PIN to a private PIN of 8 to 12 digits, with varying digits');
const cookieSecurity=production?'; Secure':'';
const listenHost=process.env.HOST||(production?'0.0.0.0':'127.0.0.1');
const businessDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const management=['owner','manager'],finance=['owner','manager','accounting'],operational=['owner','manager','purchasing','retail','packing'];
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function integer(value,name,min=1,max=100000){if(!Number.isSafeInteger(value)||value<min||value>max)fail(`${name} must be an integer from ${min} to ${max}`);return value;}
function text(value,name,max=120){if(typeof value!=='string'||!value.trim()||value.length>max)fail(`Invalid ${name}`);return value.trim();}
function optional(value,max=500){if(value===undefined)return '';if(typeof value!=='string'||value.length>max)fail('Invalid text field');return value.trim();}
function date(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T00:00:00Z'))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value)fail('Invalid date');return value;}
function passwordHash(value){const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(value,salt,64).toString('hex');}
function passwordCheck(value,hash){const [salt,digest]=hash.split(':');return crypto.timingSafeEqual(crypto.scryptSync(value,salt,64),Buffer.from(digest,'hex'));}
function allow(user,roles){if(!roles.includes(user.role))fail('Your role cannot perform this action',403);}
async function branchAccess(user,b){integer(b,'Branch');if(!await one('SELECT 1 FROM user_branches WHERE user_id=$1 AND branch_id=$2',user.id,b))fail('You do not have access to this branch',403);return b;}
async function publicUser(u){return {id:u.id,name:u.name,username:u.username,role:u.role,branches:await all('SELECT b.* FROM branches b JOIN user_branches ub ON ub.branch_id=b.id WHERE ub.user_id=$1 ORDER BY b.id',u.id)};}
async function audit(u,action,details){await run('INSERT INTO audit_logs(user_id,action,details,created_at) VALUES($1,$2,$3,$4)',u?.id||null,action,JSON.stringify(details),now());}
async function move(u,b,p,delta,reason,reference){const result=await run('UPDATE inventory SET quantity=quantity+$1 WHERE branch_id=$2 AND product_id=$3 AND quantity+$1>=0',delta,b,p);if(!result.changes)fail('Insufficient stock or product not assigned to this branch',409);await run('INSERT INTO stock_movements(branch_id,product_id,delta,reason,reference,user_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',b,p,delta,reason,String(reference),u?.id||null,now());}
async function replenish(b){
  const low=await all('SELECT i.*,p.supplier_id FROM inventory i JOIN products p ON p.id=i.product_id WHERE i.branch_id=$1',b);
  for(const p of low){
    if(p.quantity>p.reorder_level||!p.reorder_level){await run("UPDATE replenishment SET status='resolved' WHERE branch_id=$1 AND product_id=$2 AND status='open'",b,p.product_id);continue;}
    const incoming=await one("SELECT COALESCE(SUM(pi.quantity-pi.received_quantity),0) AS n FROM purchase_items pi JOIN purchase_orders po ON po.id=pi.order_id WHERE po.branch_id=$1 AND pi.product_id=$2 AND po.status IN ('pending','approved')",b,p.product_id);
    const requested=await one("SELECT COALESCE(SUM(quantity),0) AS n FROM stock_requests WHERE branch_id=$1 AND product_id=$2 AND status IN ('pending','approved')",b,p.product_id);
    const quantity=Math.max(0,2*p.reorder_level-p.quantity-incoming.n-requested.n);
    if(!quantity){await run("UPDATE replenishment SET status='resolved' WHERE branch_id=$1 AND product_id=$2 AND status='open'",b,p.product_id);continue;}
    await run("INSERT INTO replenishment(branch_id,product_id,quantity,created_at) VALUES($1,$2,$3,$4) ON CONFLICT(branch_id,product_id) WHERE status='open' DO UPDATE SET quantity=excluded.quantity",b,p.product_id,quantity,now());
  }
}
async function products(b,u){const rows=await all('SELECT p.*,i.quantity,i.reorder_level FROM products p JOIN inventory i ON i.product_id=p.id WHERE i.branch_id=$1 ORDER BY p.id',b);return rows.map(p=>{if(['retail','packing'].includes(u.role)){const {cost_cents,...safe}=p;return safe;}return p;});}
async function seed(){
  await transaction(async()=>{
    if(await one('SELECT id FROM users LIMIT 1'))return;
    const sqlitePath=path.join(root,'data','shimmery.sqlite');
    if(!production&&schema==='public'&&fs.existsSync(sqlitePath)){
      const {DatabaseSync}=require('node:sqlite');const old=new DatabaseSync(sqlitePath,{readOnly:true});
      try{for(const table of ['branches','users','user_branches','suppliers','products','inventory','sales','sale_items','returns','purchase_orders','purchase_items','deliveries','employees','attendance','audit_logs']){
        for(const row of old.prepare(`SELECT * FROM ${table}`).all()){const columns=Object.keys(row);await run(`INSERT INTO ${table}(${columns.join(',')}) VALUES(${columns.map((_,i)=>'$'+(i+1)).join(',')})`,...Object.values(row));}
        if(table!=='user_branches'&&table!=='inventory'&&table!=='purchase_items'){await one(`SELECT setval(pg_get_serial_sequence('${table}','id'),COALESCE(MAX(id),1),MAX(id) IS NOT NULL) FROM ${table}`);}
      }}finally{old.close();}
      await audit(null,'database.demo-import',{source:'Existing local SQLite demo',legacy_corporate_data:false});
    }else{
      for(const name of ['Main Store – Masbate City','Aroroy','Cataingan','Cawayan','Masbate City'])await run('INSERT INTO branches(name) VALUES($1)',name);
      for(const role of ['owner','manager','purchasing','accounting','retail','packing']){const u=await run('INSERT INTO users(username,name,role,password_hash) VALUES($1,$2,$3,$4) RETURNING id',role,role[0].toUpperCase()+role.slice(1)+' Demo',role,passwordHash(seedPin));for(const b of ['retail','packing'].includes(role)?[1]:[1,2,3,4,5])await run('INSERT INTO user_branches VALUES($1,$2)',u.id,b);}
      for(const name of ['Masbate Grains Trading','Visayas Wholesale Co.','Bicol Packaging Supply'])await run('INSERT INTO suppliers(name,terms) VALUES($1,$2)',name,'30 days');
      for(const p of [['P-001','Rice 25kg',125000,1,12,20],['P-002','Cooking oil 1L',9800,2,60,30],['P-003','Canned sardines',2400,2,18,50],['P-004','Laundry soap bar',1500,3,200,80],['P-005','Sugar 1kg',7200,1,25,40]]){const r=await run('INSERT INTO products(code,name,price_cents,supplier_id) VALUES($1,$2,$3,$4) RETURNING id',...p.slice(0,4));for(let b=1;b<=5;b++)await run('INSERT INTO inventory VALUES($1,$2,$3,$4)',b,r.id,p[4],p[5]);}
      for(const e of [['Ana Reyes',1,61000],['Ben Santos',1,56000],['Cris Dela Cruz',2,59000],['Dina Lopez',3,57000],['Eli Ramos',4,58000],['Fe Mendoza',5,60000]])await run('INSERT INTO employees(name,branch_id,daily_rate_cents) VALUES($1,$2,$3)',...e);
    }
    await run('UPDATE products SET cost_cents=ROUND(price_cents*0.7) WHERE cost_cents=0');
    await run('UPDATE purchase_items SET unit_cost_cents=p.cost_cents FROM products p WHERE p.id=purchase_items.product_id AND purchase_items.unit_cost_cents=0');
  });
  await transaction(async()=>{
    for(let b=2;b<=5;b++)for(const role of ['retail','packing']){const username=role+'_'+b;if(!await one('SELECT id FROM users WHERE username=$1',username)){const r=await run('INSERT INTO users(username,name,role,password_hash) VALUES($1,$2,$3,$4) RETURNING id',username,role+' Branch '+b,role,passwordHash(seedPin));await run('INSERT INTO user_branches VALUES($1,$2)',r.id,b);}}
    for(let b=1;b<=5;b++)await replenish(b);
  });
}
const loginAttempts=new Map();
function sessionHash(req){const token=/(?:^|;\s*)sid=([a-f0-9]+)/.exec(req.headers.cookie||'')?.[1];return token?crypto.createHash('sha256').update(token).digest('hex'):null;}
async function auth(req){const hash=sessionHash(req);if(!hash)fail('Please log in',401);const user=await one('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>$2',hash,Date.now());if(!user)fail('Session expired. Please log in',401);return user;}
async function body(req){let value='';for await(const chunk of req){value+=chunk;if(value.length>131072)fail('Request too large',413);}try{const input=JSON.parse(value||'{}');if(!input||typeof input!=='object'||Array.isArray(input))fail('Expected a JSON object');return input;}catch(e){if(e.status)throw e;fail('Invalid JSON');}}
function json(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data));}
async function saleCreate(u,b,input,wholesale=null){return transaction(async()=>{
  const key=text(input.client_key,'Transaction key',100),existing=await one('SELECT * FROM sales WHERE client_key=$1',key);
  if(existing){if(existing.user_id!==u.id||existing.branch_id!==b)fail('Transaction key already used',409);return {...existing,items:await all('SELECT si.*,p.name FROM sale_items si JOIN products p ON p.id=si.product_id WHERE sale_id=$1',existing.id),duplicate:true};}
  if(!Array.isArray(input.items)||!input.items.length||input.items.length>100)fail('Add products to the sale');
  const seen=new Set(),items=[];for(const i of input.items){integer(i.product_id,'Product');integer(i.quantity,'Quantity',1,10000);if(seen.has(i.product_id))fail('Combine duplicate product lines');seen.add(i.product_id);const p=await one('SELECT p.*,i.quantity FROM products p JOIN inventory i ON i.product_id=p.id WHERE p.id=$1 AND i.branch_id=$2',i.product_id,b);if(!p)fail('Product not found',404);if(p.quantity<i.quantity)fail('Insufficient stock for '+p.name,409);if(input.offline===true&&i.expected_price_cents!==p.price_cents)fail('Price changed for '+p.name+'; review the pending sale',409);items.push({product_id:p.id,name:p.name,quantity:i.quantity,price_cents:wholesale?integer(i.price_cents,'Quote price',0,100000000):p.price_cents});}
  const total=items.reduce((n,i)=>n+i.quantity*i.price_cents,0);integer(total,'Sale total',0,2000000000);
  let recorded=null;if(input.offline_recorded_at){recorded=text(input.offline_recorded_at,'Offline timestamp',40);if(!Number.isFinite(Date.parse(recorded))||Date.parse(recorded)>Date.now()+300000)fail('Invalid offline timestamp');}
  const created=now(),id=(await run('INSERT INTO sales(client_key,branch_id,user_id,total_cents,created_at,kind,offline_recorded_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',key,b,u.id,total,created,wholesale?'wholesale':'retail',recorded)).id;
  const receipt='R-'+String(id).padStart(6,'0');await run('UPDATE sales SET receipt=$1 WHERE id=$2',receipt,id);
  for(const i of items){await run('INSERT INTO sale_items(sale_id,product_id,quantity,price_cents) VALUES($1,$2,$3,$4)',id,i.product_id,i.quantity,i.price_cents);await move(u,b,i.product_id,-i.quantity,'sale',receipt);}
  await replenish(b);await audit(u,'sale.created',{receipt,branch:b,total_cents:total,offline:input.offline===true,kind:wholesale?'wholesale':'retail'});return {id,receipt,branch_id:b,total_cents:total,created_at:created,items};
});}
async function orderCreate(u,b,supplier,items){integer(supplier,'Supplier');if(!await one('SELECT id FROM suppliers WHERE id=$1',supplier))fail('Supplier not found',404);if(!Array.isArray(items)||!items.length||items.length>100)fail('Order needs products');
  const id=(await run('INSERT INTO purchase_orders(branch_id,supplier_id,created_by,created_at) VALUES($1,$2,$3,$4) RETURNING id',b,supplier,u.id,now())).id;const seen=new Set();
  for(const i of items){integer(i.product_id,'Product');integer(i.quantity,'Quantity',1,10000);if(seen.has(i.product_id))fail('Duplicate order product');seen.add(i.product_id);const p=await one('SELECT * FROM products WHERE id=$1',i.product_id);if(!p)fail('Product not found',404);const cost=i.unit_cost_cents===undefined?p.cost_cents:integer(i.unit_cost_cents,'Unit cost',0,100000000);integer(cost*i.quantity,'Line total',0,2000000000);await run('INSERT INTO purchase_items(order_id,product_id,quantity,unit_cost_cents) VALUES($1,$2,$3,$4)',id,p.id,i.quantity,cost);}
  await replenish(b);await audit(u,'order.created',{id,branch:b});return {id};
}
function payrollEstimate(employee,input){integer(input.days,'Days worked',0,31);integer(input.advance_cents,'Cash advance',0,100000000);const gross=employee.daily_rate_cents*input.days;integer(gross,'Gross',0,2000000000);const sss=Math.round(gross*.05),ph=Math.round(gross*.025),pi=Math.min(20000,Math.round(gross*.02));return {employee,gross_cents:gross,sss_cents:sss,philhealth_cents:ph,pagibig_cents:pi,advance_cents:input.advance_cents,net_cents:gross-sss-ph-pi-input.advance_cents,note:'Illustrative school-demo deductions; not statutory payroll rates. Days worked are manually entered.'};}
async function transfer(u,source,destination,p,quantity,requestId,key){await branchAccess(u,source);await branchAccess(u,destination);if(source===destination)fail('Choose different branches');integer(p,'Product');integer(quantity,'Quantity',1,10000);
  if(key){const existing=await one('SELECT * FROM transfers WHERE client_key=$1',key);if(existing){if(existing.user_id!==u.id||existing.source_branch!==source||existing.destination_branch!==destination||existing.product_id!==p||existing.quantity!==quantity)fail('Transfer key already used',409);return {...existing,duplicate:true};}}
  const id=(await run('INSERT INTO transfers(source_branch,destination_branch,product_id,quantity,request_id,client_key,user_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',source,destination,p,quantity,requestId,key,u.id,now())).id;
  await move(u,source,p,-quantity,'transfer-out',id);await move(u,destination,p,quantity,'transfer-in',id);if(requestId)await run("UPDATE stock_requests SET status='fulfilled' WHERE id=$1",requestId);await replenish(source);await replenish(destination);await audit(u,'stock.transferred',{id,source,destination,product:p,quantity});return {id};
}
async function api(req,res,url){const route=url.pathname,method=req.method,input=method==='POST'?await body(req):{};
  if(route==='/api/login'&&method==='POST'){
    const username=text(input.username,'Username',40).toLowerCase(),password=text(input.password,'PIN',128),key=req.socket.remoteAddress+':'+username,attempt=loginAttempts.get(key);
    if(attempt&&attempt.until>Date.now()&&attempt.count>=10)fail('Too many attempts. Try again in 5 minutes',429);
    const u=await one('SELECT * FROM users WHERE username=$1',username);if(!u||!passwordCheck(password,u.password_hash)){const a=attempt&&attempt.until>Date.now()?attempt:{count:0,until:Date.now()+300000};a.count++;loginAttempts.set(key,a);fail('Username or PIN is incorrect',401);}loginAttempts.delete(key);
    const token=crypto.randomBytes(32).toString('hex');await run('DELETE FROM sessions WHERE expires_at<=$1',Date.now());await run('INSERT INTO sessions VALUES($1,$2,$3)',crypto.createHash('sha256').update(token).digest('hex'),u.id,Date.now()+8*3600000);
    return json(res,200,await publicUser(u),{'Set-Cookie':`sid=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${cookieSecurity}`});
  }
  const u=await auth(req),branch=()=>branchAccess(u,Number(method==='GET'?url.searchParams.get('branch'):input.branch));
  if(route==='/api/me'&&method==='GET')return json(res,200,await publicUser(u));
  if(route==='/api/sync-status'&&method==='GET'){allow(u,['manager','retail']);const sale=await transaction(()=>one('SELECT id,receipt,user_id FROM sales WHERE client_key=$1',text(url.searchParams.get('client_key'),'Transaction key',100)));if(sale&&sale.user_id!==u.id)fail('Transaction belongs to another account',403);return json(res,200,{exists:!!sale,receipt:sale?.receipt});}
  if(route==='/api/attendance/summary'&&method==='GET'){allow(u,finance);const b=await branch(),start=date(url.searchParams.get('start')),end=date(url.searchParams.get('end'));if(start>end)fail('Invalid period');return json(res,200,await all('SELECT e.id,e.name,COUNT(a.id) AS completed_days FROM employees e LEFT JOIN attendance a ON a.employee_id=e.id AND a.work_date>=$1 AND a.work_date<=$2 AND a.time_out IS NOT NULL WHERE e.branch_id=$3 GROUP BY e.id ORDER BY e.name',start,end,b));}
  if(route==='/api/logout'&&method==='POST'){await run('DELETE FROM sessions WHERE token_hash=$1',sessionHash(req));return json(res,200,{ok:true},{'Set-Cookie':'sid=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'+cookieSecurity});}
  if(route==='/api/products'&&method==='GET'){allow(u,operational);return json(res,200,await products(await branch(),u));}
  if(route==='/api/reorder-levels'&&method==='POST'){allow(u,['owner','manager','purchasing']);const b=await branch();if(!Array.isArray(input.items)||!input.items.length||input.items.length>1000)fail('Provide reorder levels');await transaction(async()=>{for(const i of input.items){integer(i.product_id,'Product');integer(i.reorder_level,'Reorder level',0,10000);const r=await run('UPDATE inventory SET reorder_level=$1 WHERE branch_id=$2 AND product_id=$3',i.reorder_level,b,i.product_id);if(!r.changes)fail('Product not found',404);}await replenish(b);await audit(u,'reorder-levels.updated',{branch:b,items:input.items});});return json(res,200,{ok:true});}
  if(route==='/api/invoices'&&method==='GET'){allow(u,finance);return json(res,200,await all('SELECT inv.*,o.branch_id,s.name AS supplier_name,COALESCE(SUM(pi.quantity*pi.unit_cost_cents),0) AS order_total_cents FROM supplier_invoices inv JOIN purchase_orders o ON o.id=inv.order_id JOIN suppliers s ON s.id=o.supplier_id LEFT JOIN purchase_items pi ON pi.order_id=o.id WHERE o.branch_id=$1 GROUP BY inv.id,o.branch_id,s.name ORDER BY inv.id DESC',await branch()));}
  if(route==='/api/invoices'&&method==='POST'){allow(u,finance);const b=await branch();integer(input.order_id,'Purchase order');const result=await transaction(async()=>{if(!await one("SELECT id FROM purchase_orders WHERE id=$1 AND branch_id=$2 AND status IN ('approved','received')",input.order_id,b))fail('Choose an approved or received purchase order',409);const id=(await run('INSERT INTO supplier_invoices(order_id,invoice_number,amount_cents,invoice_date,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',input.order_id,text(input.invoice_number,'Invoice number',80),integer(input.amount_cents,'Invoice amount',0,2000000000),date(input.invoice_date),u.id,now())).id;await audit(u,'invoice.recorded',{id,order:input.order_id});return {id};});return json(res,201,result);}
  if(route==='/api/products'&&method==='POST'){allow(u,management);const b=await branch();const id=await transaction(async()=>{const supplier=integer(input.supplier_id,'Supplier');const p=(await run('INSERT INTO products(code,name,price_cents,cost_cents,supplier_id) VALUES($1,$2,$3,$4,$5) RETURNING id',text(input.code,'Product code',40),text(input.name,'Product name'),integer(input.price_cents,'Price',0,100000000),integer(input.cost_cents,'Cost',0,100000000),supplier)).id;for(const x of await all('SELECT id FROM branches'))await run('INSERT INTO inventory VALUES($1,$2,0,$3)',x.id,p,integer(input.reorder_level,'Reorder level',0,10000));const opening=integer(input.opening_quantity,'Opening stock',0,100000);if(opening)await move(u,b,p,opening,'opening','catalog');for(const x of await all('SELECT id FROM branches'))await replenish(x.id);await audit(u,'product.created',{id:p});return p;});return json(res,201,{id});}
  if(route==='/api/products/update'&&method==='POST'){allow(u,management);const b=await branch();integer(input.product_id,'Product');await transaction(async()=>{const r=await run('UPDATE products SET name=$1,price_cents=$2,cost_cents=$3,supplier_id=$4 WHERE id=$5',text(input.name,'Product name'),integer(input.price_cents,'Price',0,100000000),integer(input.cost_cents,'Cost',0,100000000),integer(input.supplier_id,'Supplier'),input.product_id);if(!r.changes)fail('Product not found',404);await run('UPDATE inventory SET reorder_level=$1 WHERE branch_id=$2 AND product_id=$3',integer(input.reorder_level,'Reorder level',0,10000),b,input.product_id);await replenish(b);await audit(u,'product.updated',{id:input.product_id,branch:b});});return json(res,200,{ok:true});}
  if(route==='/api/inventory/adjust'&&method==='POST'){allow(u,management);const b=await branch();integer(input.product_id,'Product');integer(input.delta,'Stock adjustment',-100000,100000);if(!input.delta)fail('Adjustment cannot be zero');const reason=text(input.reason,'Adjustment reason',200);await transaction(async()=>{await move(u,b,input.product_id,input.delta,'adjustment',reason);await replenish(b);await audit(u,'inventory.adjusted',{branch:b,product:input.product_id,delta:input.delta,reason});});return json(res,200,{ok:true});}
  if(route==='/api/dashboard'&&method==='GET'){
    allow(u,['owner','manager','purchasing','accounting']);const b=await branch(),today=businessDate(),start=new Date(today+'T00:00:00+08:00').toISOString(),end=new Date(Date.parse(start)+86400000).toISOString();
    const s=await one('SELECT COALESCE(SUM(total_cents),0) AS total,COUNT(*) AS count FROM sales WHERE branch_id=$1 AND created_at>=$2 AND created_at<$3',b,start,end),r=await one('SELECT COALESCE(SUM(r.amount_cents),0) AS total FROM returns r JOIN sales s ON s.id=r.sale_id WHERE s.branch_id=$1 AND r.created_at>=$2 AND r.created_at<$3',b,start,end),a=await one('SELECT COUNT(*) AS count FROM attendance a JOIN employees e ON e.id=a.employee_id WHERE e.branch_id=$1 AND a.work_date=$2 AND a.time_out IS NULL',b,today),low=(await all('SELECT p.name,i.* FROM inventory i JOIN products p ON p.id=i.product_id WHERE i.branch_id=$1 AND i.quantity<=i.reorder_level',b));
    const branches=[];for(const x of (await publicUser(u)).branches)branches.push({...x,sales:(await one('SELECT COUNT(*) AS count FROM sales WHERE branch_id=$1',x.id)).count});return json(res,200,{today,sales_cents:finance.includes(u.role)?s.total:null,refunds_cents:finance.includes(u.role)?r.total:null,active_staff:finance.includes(u.role)?a.count:null,low_stock:low,branches});
  }
  if(route==='/api/suppliers'&&method==='GET'){allow(u,['owner','manager','purchasing','packing']);return json(res,200,await all('SELECT * FROM suppliers ORDER BY name'));}
  if(route==='/api/suppliers'&&method==='POST'){allow(u,['owner','purchasing']);const id=await transaction(async()=>{const r=await run('INSERT INTO suppliers(name,contact,items,terms) VALUES($1,$2,$3,$4) RETURNING id',text(input.name,'Supplier name'),optional(input.contact),optional(input.items),optional(input.terms));await audit(u,'supplier.created',{id:r.id});return r.id;});return json(res,201,{id});}
  if(route==='/api/sales'&&method==='POST'){allow(u,['manager','retail']);const s=await saleCreate(u,await branch(),input);return json(res,s.duplicate?200:201,s);}
  if(route==='/api/receipts'&&method==='GET'){allow(u,['manager','retail']);const b=await branch(),s=await one('SELECT * FROM sales WHERE receipt=$1 AND branch_id=$2',url.searchParams.get('receipt'),b);if(!s)fail('Receipt not found in this branch',404);const items=await all('SELECT si.*,p.name FROM sale_items si JOIN products p ON p.id=si.product_id WHERE sale_id=$1',s.id);return json(res,200,{...s,items,eligible:Date.now()-Date.parse(s.created_at)<=7*86400000&&items.some(i=>i.returned_quantity<i.quantity)});}
  if(route==='/api/returns'&&method==='POST'){allow(u,['manager','retail']);const b=await branch();if(!['refund','defective'].includes(input.kind))fail('Invalid return type');const r=await transaction(async()=>{const s=await one('SELECT * FROM sales WHERE receipt=$1 AND branch_id=$2',input.receipt,b);if(!s)fail('Receipt not found in this branch',404);if(Date.now()-Date.parse(s.created_at)>7*86400000)fail('Receipt is outside the 7-day return window',409);const items=await all('SELECT * FROM sale_items WHERE sale_id=$1',s.id);let amount=0;for(const i of items){const remaining=i.quantity-i.returned_quantity;amount+=remaining*i.price_cents;if(remaining&&input.kind==='refund')await move(u,b,i.product_id,remaining,'refund',s.receipt);await run('UPDATE sale_items SET returned_quantity=quantity WHERE id=$1',i.id);}if(!amount)fail('This receipt has already been returned',409);const id=(await run('INSERT INTO returns(sale_id,user_id,kind,amount_cents,created_at) VALUES($1,$2,$3,$4,$5) RETURNING id',s.id,u.id,input.kind,amount,now())).id;await replenish(b);await audit(u,'return.created',{receipt:s.receipt,kind:input.kind,amount_cents:amount});return {id,amount_cents:amount};});return json(res,201,r);}
  if(route==='/api/orders'&&method==='GET'){allow(u,['owner','manager','purchasing','packing']);const b=await branch(),rows=await all('SELECT o.*,s.name AS supplier_name FROM purchase_orders o JOIN suppliers s ON s.id=o.supplier_id WHERE branch_id=$1 ORDER BY o.id DESC',b);for(const o of rows){o.items=await all('SELECT i.*,p.name FROM purchase_items i JOIN products p ON p.id=i.product_id WHERE order_id=$1',o.id);o.total_cents=o.items.reduce((n,i)=>n+i.quantity*i.unit_cost_cents,0);if(u.role==='packing'){delete o.total_cents;o.items=o.items.map(({unit_cost_cents,...i})=>i);}}return json(res,200,rows);}
  if(route==='/api/orders'&&method==='POST'){allow(u,['purchasing']);const b=await branch();return json(res,201,await transaction(()=>orderCreate(u,b,input.supplier_id,input.items)));}
  if(route==='/api/orders/approve'&&method==='POST'){allow(u,management);const b=await branch();integer(input.order_id,'Order');await transaction(async()=>{const r=await run("UPDATE purchase_orders SET status='approved',approved_by=$1 WHERE id=$2 AND branch_id=$3 AND status='pending'",u.id,input.order_id,b);if(!r.changes)fail('Only pending orders in this branch can be approved',409);await audit(u,'order.approved',{id:input.order_id});});return json(res,200,{ok:true});}
  if(route==='/api/deliveries'&&method==='POST'){allow(u,['manager','purchasing','packing']);const b=await branch();integer(input.order_id,'Order');integer(input.product_id,'Product');integer(input.quantity,'Received quantity',1,10000);integer(input.damaged_quantity,'Damaged quantity',0,input.quantity);await transaction(async()=>{if(!await one("SELECT id FROM purchase_orders WHERE id=$1 AND branch_id=$2 AND status='approved'",input.order_id,b))fail('Choose an approved order',409);const i=await one('SELECT * FROM purchase_items WHERE order_id=$1 AND product_id=$2',input.order_id,input.product_id);if(!i||i.received_quantity+input.quantity>i.quantity)fail('Delivery exceeds remaining order quantity',409);await run('INSERT INTO deliveries(order_id,product_id,quantity,damaged_quantity,received_by,created_at) VALUES($1,$2,$3,$4,$5,$6)',input.order_id,input.product_id,input.quantity,input.damaged_quantity,u.id,now());await run('UPDATE purchase_items SET received_quantity=received_quantity+$1 WHERE order_id=$2 AND product_id=$3',input.quantity,input.order_id,input.product_id);await move(u,b,input.product_id,input.quantity-input.damaged_quantity,'delivery',input.order_id);if(!await one('SELECT 1 FROM purchase_items WHERE order_id=$1 AND received_quantity<quantity',input.order_id))await run("UPDATE purchase_orders SET status='received' WHERE id=$1",input.order_id);await replenish(b);await audit(u,'delivery.created',{order:input.order_id,received:input.quantity,damaged:input.damaged_quantity});});return json(res,201,{ok:true});}
  if(route==='/api/replenishment'&&method==='GET'){allow(u,['owner','manager','purchasing']);const b=await branch();await transaction(()=>replenish(b));return json(res,200,await all("SELECT r.*,p.name,p.supplier_id,p.cost_cents,i.quantity AS stock FROM replenishment r JOIN products p ON p.id=r.product_id JOIN inventory i ON i.branch_id=r.branch_id AND i.product_id=r.product_id WHERE r.branch_id=$1 AND r.status='open' ORDER BY r.id",b));}
  if(route==='/api/replenishment/order'&&method==='POST'){allow(u,['purchasing']);const b=await branch();integer(input.proposal_id,'Proposal');const result=await transaction(async()=>{const p=await one("SELECT r.*,p.supplier_id FROM replenishment r JOIN products p ON p.id=r.product_id WHERE r.id=$1 AND r.branch_id=$2 AND r.status='open'",input.proposal_id,b);if(!p)fail('Open proposal not found',409);const order=await orderCreate(u,b,p.supplier_id,[{product_id:p.product_id,quantity:p.quantity}]);await run("UPDATE replenishment SET status='ordered',order_id=$1 WHERE id=$2",order.id,p.id);return order;});return json(res,201,result);}
  if(route==='/api/stock-requests'&&method==='GET'){allow(u,operational);return json(res,200,await all('SELECT r.*,p.name,s.name AS source_name FROM stock_requests r JOIN products p ON p.id=r.product_id JOIN branches s ON s.id=r.source_branch WHERE r.branch_id=$1 ORDER BY r.id DESC',await branch()));}
  if(route==='/api/stock-requests'&&method==='POST'){allow(u,operational);const b=await branch(),source=integer(input.source_branch,'Source branch');if(b===source)fail('Choose a different source branch');integer(input.product_id,'Product');integer(input.quantity,'Quantity',1,10000);if(!await one('SELECT id FROM branches WHERE id=$1',source))fail('Source branch not found',404);const id=await transaction(async()=>{const r=await run('INSERT INTO stock_requests(branch_id,source_branch,product_id,quantity,requested_by,created_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',b,source,input.product_id,input.quantity,u.id,now());await replenish(b);await audit(u,'stock.requested',{id:r.id,branch:b,source});return r.id;});return json(res,201,{id});}
  if(route==='/api/stock-requests/approve'&&method==='POST'){allow(u,management);const b=await branch();integer(input.request_id,'Request');await transaction(async()=>{const r=await run("UPDATE stock_requests SET status='approved',approved_by=$1 WHERE id=$2 AND branch_id=$3 AND status='pending'",u.id,input.request_id,b);if(!r.changes)fail('Pending request not found',409);await audit(u,'stock.request-approved',{id:input.request_id});});return json(res,200,{ok:true});}
  if(route==='/api/transfers'&&method==='POST'){allow(u,management);const result=await transaction(async()=>{if(input.request_id){integer(input.request_id,'Request');const r=await one('SELECT * FROM stock_requests WHERE id=$1',input.request_id);if(!r)fail('Request not found',404);await branchAccess(u,r.branch_id);if(r.status==='fulfilled'){return {...await one('SELECT * FROM transfers WHERE request_id=$1',r.id),duplicate:true};}if(r.status!=='approved')fail('Approve the request before transferring stock',409);return transfer(u,r.source_branch,r.branch_id,r.product_id,r.quantity,r.id,null);}return transfer(u,integer(input.source_branch,'Source'),integer(input.destination_branch,'Destination'),input.product_id,input.quantity,null,text(input.client_key,'Transfer key',100));});return json(res,result.duplicate?200:201,result);}
  if(route==='/api/movements'&&method==='GET'){allow(u,operational);return json(res,200,await all('SELECT m.*,p.name FROM stock_movements m JOIN products p ON p.id=m.product_id WHERE branch_id=$1 ORDER BY m.id DESC LIMIT 100',await branch()));}
  if(route==='/api/employees'&&method==='GET'){allow(u,finance);return json(res,200,await all('SELECT * FROM employees WHERE branch_id=$1 ORDER BY name',await branch()));}
  if(route==='/api/employees'&&method==='POST'){allow(u,management);const b=await branch();const id=await transaction(async()=>{const r=await run('INSERT INTO employees(name,branch_id,daily_rate_cents) VALUES($1,$2,$3) RETURNING id',text(input.name,'Employee name'),b,integer(input.daily_rate_cents,'Daily rate',0,10000000));await audit(u,'employee.created',{id:r.id,branch:b});return r.id;});return json(res,201,{id});}
  if(route==='/api/employees/update'&&method==='POST'){allow(u,management);const b=await branch();integer(input.employee_id,'Employee');await transaction(async()=>{const r=await run('UPDATE employees SET name=$1,daily_rate_cents=$2 WHERE id=$3 AND branch_id=$4',text(input.name,'Employee name'),integer(input.daily_rate_cents,'Daily rate',0,10000000),input.employee_id,b);if(!r.changes)fail('Employee not found',404);await audit(u,'employee.updated',{id:input.employee_id});});return json(res,200,{ok:true});}
  if(route==='/api/attendance'&&method==='GET'){allow(u,finance);const b=await branch(),d=date(url.searchParams.get('date')||businessDate());return json(res,200,await all('SELECT e.id AS employee_id,e.name,e.branch_id,a.time_in,a.time_out,a.source FROM employees e LEFT JOIN attendance a ON a.employee_id=e.id AND a.work_date=$1 WHERE e.branch_id=$2 ORDER BY e.name',d,b));}
  if(route==='/api/attendance/scan'&&method==='POST'){allow(u,finance);const b=await branch();integer(input.employee_id,'Employee');if(!['in','out'].includes(input.action))fail('Choose time in or time out');const record=await transaction(async()=>{if(!await one('SELECT id FROM employees WHERE id=$1 AND branch_id=$2',input.employee_id,b))fail('Employee not found in branch',404);const d=businessDate(),current=await one('SELECT * FROM attendance WHERE employee_id=$1 AND work_date=$2',input.employee_id,d);if(input.action==='in'){if(current)fail('Employee already timed in today',409);await run('INSERT INTO attendance(employee_id,work_date,time_in,recorded_by) VALUES($1,$2,$3,$4)',input.employee_id,d,now(),u.id);}else{if(!current||current.time_out)fail('Employee must have an open time-in record today',409);await run('UPDATE attendance SET time_out=$1 WHERE id=$2',now(),current.id);}await audit(u,'attendance.simulated-scan',{employee:input.employee_id,action:input.action});return one('SELECT * FROM attendance WHERE employee_id=$1 AND work_date=$2',input.employee_id,d);});return json(res,201,record);}
  if(route==='/api/payroll'&&method==='POST'){allow(u,finance);const b=await branch();integer(input.employee_id,'Employee');const e=await one('SELECT * FROM employees WHERE id=$1 AND branch_id=$2',input.employee_id,b);if(!e)fail('Employee not found',404);return json(res,200,payrollEstimate(e,input));}
  if(route==='/api/payroll-records'&&method==='GET'){allow(u,finance);return json(res,200,await all('SELECT * FROM payroll_records WHERE branch_id=$1 ORDER BY period_start DESC,id DESC',await branch()));}
  if(route==='/api/payroll-records'&&method==='POST'){allow(u,finance);const b=await branch(),start=date(input.period_start),end=date(input.period_end);if(start>end||Date.parse(end)-Date.parse(start)>30*86400000)fail('Pay period must cover 1 to 31 days');const maxDays=(Date.parse(end)-Date.parse(start))/86400000+1;integer(input.days,'Days worked',0,maxDays);integer(input.employee_id,'Employee');const result=await transaction(async()=>{const e=await one('SELECT * FROM employees WHERE id=$1 AND branch_id=$2',input.employee_id,b);if(!e)fail('Employee not found',404);if(await one('SELECT id FROM payroll_records WHERE employee_id=$1 AND period_start<=$2 AND period_end>=$3',e.id,end,start))fail('A saved payroll record overlaps this employee pay period',409);const p=payrollEstimate(e,input);const id=(await run('INSERT INTO payroll_records(branch_id,employee_id,employee_name,period_start,period_end,days,daily_rate_cents,gross_cents,sss_cents,philhealth_cents,pagibig_cents,advance_cents,net_cents,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id',b,e.id,e.name,start,end,input.days,e.daily_rate_cents,p.gross_cents,p.sss_cents,p.philhealth_cents,p.pagibig_cents,p.advance_cents,p.net_cents,u.id,now())).id;await audit(u,'payroll.saved',{id,employee:e.id,start,end});return one('SELECT * FROM payroll_records WHERE id=$1',id);});return json(res,201,result);}
  if(route==='/api/customers'&&method==='GET'){allow(u,['owner','manager','retail','accounting']);return json(res,200,await all('SELECT * FROM customers ORDER BY name'));}
  if(route==='/api/customers'&&method==='POST'){allow(u,['owner','manager','retail']);const r=await transaction(async()=>{const r=await run('INSERT INTO customers(name,contact) VALUES($1,$2) RETURNING id',text(input.name,'Customer name'),optional(input.contact));await audit(u,'customer.created',{id:r.id});return r;});return json(res,201,{id:r.id});}
  if(route==='/api/wholesale'&&method==='GET'){allow(u,['owner','manager','retail','accounting']);const rows=await all('SELECT w.*,c.name AS customer_name FROM wholesale_orders w JOIN customers c ON c.id=w.customer_id WHERE branch_id=$1 ORDER BY w.id DESC',await branch());for(const w of rows)w.items=await all('SELECT i.*,p.name FROM wholesale_items i JOIN products p ON p.id=i.product_id WHERE order_id=$1',w.id);return json(res,200,rows);}
  if(route==='/api/wholesale'&&method==='POST'){allow(u,['owner','manager','retail']);const b=await branch();integer(input.customer_id,'Customer');if(!Array.isArray(input.items)||!input.items.length||input.items.length>100)fail('Quote needs products');const result=await transaction(async()=>{const seen=new Set();let total=0;for(const i of input.items){integer(i.product_id,'Product');integer(i.quantity,'Quantity',1,10000);integer(i.price_cents,'Quote unit price',0,100000000);if(seen.has(i.product_id))fail('Duplicate quote product');seen.add(i.product_id);total+=i.quantity*i.price_cents;}integer(total,'Quote total',0,2000000000);const id=(await run('INSERT INTO wholesale_orders(branch_id,customer_id,created_by,created_at,total_cents) VALUES($1,$2,$3,$4,$5) RETURNING id',b,input.customer_id,u.id,now(),total)).id;for(const i of input.items)await run('INSERT INTO wholesale_items VALUES($1,$2,$3,$4)',id,i.product_id,i.quantity,i.price_cents);await audit(u,'wholesale.quoted',{id,branch:b});return {id};});return json(res,201,result);}
  if(route==='/api/wholesale/accept'&&method==='POST'){allow(u,management);const b=await branch();integer(input.order_id,'Quote');await transaction(async()=>{const r=await run("UPDATE wholesale_orders SET status='accepted' WHERE id=$1 AND branch_id=$2 AND status='quote'",input.order_id,b);if(!r.changes)fail('Open quote not found',409);await audit(u,'wholesale.accepted',{id:input.order_id});});return json(res,200,{ok:true});}
  if(route==='/api/wholesale/fulfill'&&method==='POST'){allow(u,['manager','retail']);const b=await branch();integer(input.order_id,'Order');const s=await transaction(async()=>{const w=await one('SELECT * FROM wholesale_orders WHERE id=$1 AND branch_id=$2',input.order_id,b);if(!w)fail('Order not found',404);if(w.status==='fulfilled')return {...await one('SELECT * FROM sales WHERE id=$1',w.sale_id),duplicate:true};if(w.status!=='accepted')fail('Management must accept the quote first',409);const items=await all('SELECT * FROM wholesale_items WHERE order_id=$1',w.id),s=await saleCreate(u,b,{client_key:'wholesale-'+w.id,items},true);await run("UPDATE wholesale_orders SET status='fulfilled',sale_id=$1 WHERE id=$2",s.id,w.id);await audit(u,'wholesale.fulfilled',{id:w.id,sale:s.id});return s;});return json(res,s.duplicate?200:201,s);}
  if(route==='/api/reports'&&method==='GET'){allow(u,finance);const b=await branch();const sales=await one('SELECT COALESCE(SUM(total_cents),0) AS total,COUNT(*) AS count FROM sales WHERE branch_id=$1',b),refunds=await one('SELECT COALESCE(SUM(r.amount_cents),0) AS total FROM returns r JOIN sales s ON s.id=r.sale_id WHERE s.branch_id=$1',b),purchases=await one('SELECT COALESCE(SUM(i.quantity*i.unit_cost_cents),0) AS ordered,COALESCE(SUM(i.received_quantity*i.unit_cost_cents),0) AS received FROM purchase_items i JOIN purchase_orders o ON o.id=i.order_id WHERE o.branch_id=$1',b),payroll=await one('SELECT COALESCE(SUM(net_cents),0) AS total FROM payroll_records WHERE branch_id=$1',b);return json(res,200,{sales_cents:sales.total,sales_count:sales.count,refunds_cents:refunds.total,net_sales_cents:sales.total-refunds.total,purchase_ordered_cents:purchases.ordered,purchase_received_cents:purchases.received,payroll_saved_cents:payroll.total,purchase_orders:await all('SELECT o.*,s.name AS supplier_name,COALESCE(SUM(i.quantity*i.unit_cost_cents),0) AS total_cents FROM purchase_orders o JOIN suppliers s ON s.id=o.supplier_id LEFT JOIN purchase_items i ON i.order_id=o.id WHERE o.branch_id=$1 GROUP BY o.id,s.name ORDER BY o.id DESC',b),note:'Operational demo totals, not audited financial statements. No money is sent to suppliers.'});}
  if(route==='/api/users'&&method==='GET'){allow(u,management);const rows=await all('SELECT id,name,username,role FROM users ORDER BY id');for(const r of rows)r.branches=(await publicUser(r)).branches;return json(res,200,rows);}
  if(route==='/api/users'&&method==='POST'){allow(u,['owner']);const role=text(input.role,'Role',20);if(!['owner','manager','purchasing','accounting','retail','packing'].includes(role))fail('Invalid role');const username=text(input.username,'Username',40).toLowerCase();if(!/^[a-z0-9_]+$/.test(username))fail('Use letters, numbers and underscores for the username');const pin=text(input.pin,'PIN',128);if(!/^\d{4,12}$/.test(pin))fail('Use a PIN with 4 to 12 digits');if(!Array.isArray(input.branches)||!input.branches.length)fail('Assign at least one branch');for(const b of input.branches)await branchAccess(u,b);const id=await transaction(async()=>{const r=await run('INSERT INTO users(username,name,role,password_hash) VALUES($1,$2,$3,$4) RETURNING id',username,text(input.name,'Name'),role,passwordHash(pin));for(const b of new Set(input.branches))await run('INSERT INTO user_branches VALUES($1,$2)',r.id,b);await audit(u,'user.created',{id:r.id,role,branches:input.branches});return r.id;});return json(res,201,{id});}
  if(route==='/api/setup'&&method==='GET'){allow(u,management);const counts={};for(const [key,table] of Object.entries({branches:'branches',products:'products',employees:'employees',sales:'sales',audit_events:'audit_logs',payroll_records:'payroll_records',transfers:'transfers',wholesale_orders:'wholesale_orders'}))counts[key]=(await one(`SELECT COUNT(*) AS n FROM ${table}`)).n;return json(res,200,{engine:'PostgreSQL',mode:'Fresh school database; prior local demo records preserved',fingerprint:'Simulation only; no biometric data is collected',counts,recent_events:await all('SELECT a.action,a.created_at,u.name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 30')});}
  fail('API endpoint not found',404);
}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/healthz'&&req.method==='GET'){await one('SELECT 1 AS ok');return json(res,200,{ok:true});}if(url.pathname.startsWith('/api/')){if(!['GET','POST'].includes(req.method))fail('Method not allowed',405);if(req.method==='POST'&&req.headers.origin&&!['http://'+req.headers.host,'https://'+req.headers.host].includes(req.headers.origin))fail('Cross-origin request rejected',403);return await api(req,res,url);}if(req.method!=='GET')fail('Method not allowed',405);const files={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/extra.js':'extra.js','/sw.js':'sw.js','/manifest.json':'manifest.json'};if(!files[url.pathname])fail('File not found',404);res.setHeader('Cache-Control','no-cache');res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript; charset=utf-8':url.pathname.endsWith('.json')?'application/json':'text/html; charset=utf-8');let content=fs.readFileSync(path.join(root,'public',files[url.pathname]));if(files[url.pathname]==='index.html'&&production)content=content.toString().replace('School project · working local demo','School project · hosted demo').replace('Fictional demo accounts · PIN 1234','Use the username and PIN provided by your project team.').replace('id="demo"','id="demo" hidden style="display:none"');res.end(content);}catch(e){const conflict=['23505','23503','23514'].includes(e.code),status=e.status||(conflict?409:500);if(status===500)console.error('Server request error:',e.message);json(res,status,{error:e.status?e.message:conflict?'Conflicting record or invalid reference':'Server error'});}});
const ready=(async()=>{await initialize();await seed();await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(Number(process.env.PORT||3000),listenHost,resolve);});console.log('Shimmery Central (PostgreSQL): http://'+(listenHost)+':'+server.address().port);})();
ready.catch(e=>{console.error('Startup failed:',e.message);if(!process.env.TEST_SCHEMA)process.exitCode=1;});
async function close(){await new Promise(resolve=>server.close(resolve));await pool.end();}
if(!process.env.TEST_SCHEMA){process.on('SIGINT',()=>close().then(()=>process.exit()));process.on('SIGTERM',()=>close().then(()=>process.exit()));}
module.exports={server,ready,close,pool,db:{close:()=>pool.end()}};
